### ISSUE TITLE
Is it possible to provide the model with an initial guess for the parameters a,b,c and d?

### ISSUE THREAD

**Issue by SuperKogito** [JianpanHuang/KAN#2]
Is it possible to provide the model with an initial guess for the parameters? a good guess should speed up the convergence. 
Do you have any idea if this is possible ?

**Comment by JianpanHuang** [comment]
I am not sure. I did not try that.
The a,b,c,d used here are randomly sampled from [0.1:0.1:2] in this study.

Best regards,
JP
________________________________
From: Ayoub Malek ***@***.***>
Sent: Wednesday, July 10, 2024 4:41 PM
To: JianpanHuang/KAN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JianpanHuang/KAN] Is it possible to provide the model with an initial guess for the parameters a,b,c and d? (Issue #2)


Is it possible to provide the model with an initial guess for the parameters? a good guess should speed up the convergence.
Do you have any idea if this is possible ?
